SELECT ROUND(AVG(SALARY),2), MAX(SALARY), MIN(SALARY), MEDIAN(SALARY), DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY departments.department_name