SELECT EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME, EMPLOYEES.commission_pct, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.hire_date
from EMPLOYEES
INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE commission_pct != 0 AND SALARY >= 10000 AND SALARY <= 15000 AND employees.hire_date <= '11/06/2005';


