SELECT EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME, SALARY
from EMPLOYEES
INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE DEPARTMENT_NAME = 'IT' AND SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
